config/routes.rb
Rails.application.routes.draw do
  resources :chats
  resources :chat_messages, only: [:create]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :chat_messages
  before_validation(on: :create) do
    self.session_id = SecureRandom.hex(10)
  end
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :chat
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def abc
  end
end

app/controllers/chat_messages_controller.rb
class ChatMessagesController < ApplicationController
  def create
    @chat = Chat.find(params[:chat_id])
    @chat_message = @chat.chat_messages.create(chat_message_params)
    if @chat_message.save
      ChatMessageCreatedJob.perform_later(@chat_message)
      render turbo_stream: turbo_stream.append(
        "chat_messages_#{@chat.id}",
        partial: "chat_messages/chat_message",
        locals: { chat_message: @chat_message}
      )
    else

      render json: @chat_message.errors, status: :unprocessable_entity
    end
  end

  private

  def chat_message_params
    params.require(:chat_message).permit(:content)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
    @chats = Chat.all
  end

  def show
    @chat = Chat.find_by(session_id: params[:id])
  end

  def create
    @chat = Chat.create!

    redirect_to chat_path(@chat.session_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_messages_helper.rb
module ChatMessagesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chat_messages/_chat_message.html.erb
<%= chat_message.created_at %> &nbsp; &nbsp; &nbsp; &nbsp;
<%= chat_message.content %>

app/views/chats/index.html.erb
<h1>Chats with Me</h1>
<%= button_to  "create_chat",chats_path, method: :post, data: {turbo: false} %>
<% @chats.each do |chat| %>
  <a href = "<%= chat_path(chat.session_id) %>">
  <span >
    <%= chat.session_id%>
  </span>
  </a>
  <p> <%= chat.session_id%> </p>
  <p><%= chat.created_at%> </p>
  <div>
    <%= chat.chat_messages&.last&.content&.truncate(50) %>
  </div>
<% end %>

app/views/chats/show.html.erb
<h1>Chats <%= @chat.session_id %></h1>
<%= turbo_stream_from "chat_messages_#{ @chat.id }" %>
<div id = "chat_messages_<%= @chat.id%>">
  <% @chat.chat_messages.each do |message| %>
    <%= render partial: "chat_messages/chat_message", locals: { chat_message: message }  %> <br>
  <% end %>
</div>
<form method='POST' action='/chat_messages' data-controller ="chat-message-form" data-action = "turbo:submit-end->chat-message-form#reset"> 
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="chat_id" value="<%= @chat.id %>">
  <textarea name="chat_message[content]"></textarea> <br>
  <button type="submit">Send</button>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SportsDriver</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>